//
//  QuickFiColor.swift
//  QuickFi Design System — MOBILE FIRST.
//
//  Generated by scripts/gen-swift.js from tokens/source.js + tokens/values.json.
//  Do not hand-edit: `npm run build` overwrites this file and CI fails if it has
//  drifted. The scaffolding below the token list is hand-written and lives in
//  templates/QuickFiColor.swift.tmpl.
//
//  Two layers. brandGreen and brandCharcoal are PRIMITIVES: never bind a
//  component to them. Everything else is semantic — that is what components use.
//
//  Buttons are named by appearance, not rank: filled, outline, text. Ranked
//  names collided with the text emphasis ladder.
//
//  Brand green #25AB3A, oklch hue 145. Neutrals anchored on #3A3A3C, hue 286.
//  Dark background #242424, surface #2C3036 — mid-grey elevated, not near-black.
//
import SwiftUI
import UIKit

extension UIColor {
    convenience init(hex: UInt32) {
        self.init(red:   CGFloat((hex >> 16) & 0xFF) / 255.0,
                  green: CGFloat((hex >>  8) & 0xFF) / 255.0,
                  blue:  CGFloat( hex        & 0xFF) / 255.0, alpha: 1.0)
    }
    /// A dynamic colour that resolves per trait collection, so UIKit views
    /// switch mode with the system the same way the SwiftUI Color does.
    static func qf(_ light: UInt32, _ dark: UInt32) -> UIColor {
        UIColor { $0.userInterfaceStyle == .dark ? UIColor(hex: dark) : UIColor(hex: light) }
    }
}
extension Color {
    init(hex: UInt32) { self.init(UIColor(hex: hex)) }
    static func qf(_ light: UInt32, _ dark: UInt32) -> Color { Color(UIColor.qf(light, dark)) }
}

public enum QuickFiColor {

    // MARK: - Brand
    /// PRIMITIVE.
    /// The brand colour, for marks, illustration and marketing artwork.
    /// Never bind a component to this directly. It doubles as QuickFi's own seed for the runtime brand engine (tokens/brand-engine.md) — the credit-line accent and container tokens derive from a seed exactly like this one, per partner.
    public static let brandGreen = Color.qf(0x25AB3A, 0x25AB3A)
    /// PRIMITIVE.
    /// The neutral anchor; the grey ramp derives from its hue.
    /// Never bind a component to this.
    public static let brandCharcoal = Color.qf(0x3A3A3C, 0x3A3A3C)

    // MARK: - Container
    /// Every screen background.
    /// Always tinted so surface layers read by fill.
    /// Section headers only.
    public static let background = Color.qf(0xF1F1F4, 0x242424)
    /// Where all content lives: cards, sheets, list rows, dialogs, nav bars, tables.
    /// Also the fill of an OUTLINE button.
    /// In light mode this is pure white — the lightness ceiling — which is why surface-1 and surface-2 above it step BACK DOWN rather than up.
    public static let surface = Color.qf(0xFFFFFF, 0x2C3036)
    /// One elevation step above surface — content sitting on top of an already-raised layer: a tab bar or nav bar over a list of raised rows.
    /// Derived to clear a 1.10 separation floor against both surface and background, so it reads as distinct from either even if the intermediate layer isn't present.
    /// text/tertiary is NOT rated on this fill — surface's white leaves it no headroom; it lands around 4.0–4.2:1, just under the 4.5:1 floor. Use text/primary or text/secondary.
    public static let surface1 = Color.qf(0xE3E3E8, 0x393834)
    /// One elevation step above surface-1 — for content that needs to read as more prominent still. Rare; most screens never need it.
    /// Derived the same way as surface-1: clears 1.10 separation against surface-1, surface AND background.
    /// text/tertiary is NOT rated on this fill either — it lands around 3.5–3.7:1 in both modes, below the 4.5:1 text floor. Use text/primary or text/secondary here.
    public static let surface2 = Color.qf(0xD6D6DB, 0x41403C)
    /// Recessed areas INSIDE a surface: inputs, wells, disabled fields. Structural only — it does not carry a pressed or selected state; that is action/selected's job.
    /// Carries the same faint per-credit-line tint as every container token (tokens/brand-engine.md).
    /// Takes textPrimary only — textLink is measurably below the text floor on it, in every registered and synthetic credit line, and is not rated for this fill.
    /// DARKER than its parent in light, LIGHTER in dark.
    public static let subsurface = Color.qf(0xD8D8DB, 0x3C3C44)
    /// The page wash's corner tone. BRAND-DERIVED and DARK-MODE ONLY — this static value is container/background itself, so an unbranded page is flat, and so is every light page. See tokens/brand-engine.md, 'The page wash'.
    /// Never set this by hand and never paint a page gradient by hand: two radial glows (top-left and bottom-right, radius 120% of the page so they meet in the middle, haze ring at 75%, faded out at 100%) are the engine's contract, and the derived corner holds the page's OWN lightness so text stays legible on it.
    public static let backgroundWash = Color.qf(0xF1F1F4, 0x242424)
    /// The page wash's haze ring — black at 60% pre-composited over the page, so every stop of each glow is OPAQUE and renders identically on CSS, SwiftUI and Compose. BRAND-DERIVED and DARK-MODE ONLY; this static value is container/background itself.
    /// It is deliberately DARKER than container/background once derived, which for any other token would read as a hole. A hole looks recessed FROM the page; this is part of the page, and it moves every obligation the safe way — light text gains contrast, cards gain separation.
    public static let backgroundWashHaze = Color.qf(0xF1F1F4, 0x242424)

    // MARK: - Text
    /// Titles, body, values.
    /// Also the label of an OUTLINE button.
    public static let textPrimary = Color.qf(0x0B0A0F, 0xF3F3F6)
    /// Supporting copy, row detail, captions.
    public static let textSecondary = Color.qf(0x3B3B3B, 0xE6E6E6)
    /// Timestamps and hints. NOT placeholders — a placeholder sits in the container/subsurface well of an input, where this measures 3.62:1 light / 3.86:1 dark; use text/secondary.
    /// Still AA on container/background AND container/surface — and ONLY there. Everywhere else it lands 3.55-4.02:1, under the 4.5:1 floor: use text/primary or text/secondary. See the pairing table.
    public static let textTertiary = Color.qf(0x6D6D72, 0x9999A0)
    /// Disabled control labels ONLY, never content.
    /// Below AA by design — WCAG 1.4.3 exempts the text of an inactive control by name, and a disabled label that clears the active floor reads as enabled.
    public static let textDisabled = Color.qf(0xA7A7AD, 0x68686F)
    /// Label on every action/filled/* intent and on solid feedback fills.
    /// MODE-SPLIT: white in light, near-black in dark.
    public static let textOnAction = Color.qf(0xFFFFFF, 0x090C08)
    /// Label on actionFilledDisabled. Nothing else — never textDisabled, which is a content token. 4.6:1.
    public static let textOnActionDisabled = Color.qf(0x606067, 0xBABAC1)
    /// The numeral on the count badge. Nothing else.
    /// MODE-SPLIT: white in light, near-black in dark — same logic as textOnAction, kept separate so badges can retheme independently.
    public static let textOnBadge = Color.qf(0xFFFFFF, 0x090C08)
    /// Label on actionFilledSuccess. Nothing else.
    /// Mode-split, same as textOnAction: white in light, near-black in dark.
    /// The one label pairing in this system with no contrast audit behind it. On the light success fill white measures 3.42:1 and near-black 5.77:1, but near-black on a saturated mid-green reads as smudged — WCAG's luminance-only ratio does not model that. The pairing was dropped from the audit by decision; changing actionFilledSuccess will not fail a build here.
    public static let textOnActionSuccess = Color.qf(0xFFFFFF, 0x0B0A0F)
    /// Tappable text: inline links and the label of a TEXT button.
    /// Not rated on container/subsurface or actionSelected — measured 2.67-3.46:1 across the registered credit lines once BOTH are brand-derived, and never above 3.59:1 across the 216-seed sweep. Use textPrimary on either.
    /// The neutral fallback is feedback/info-text's value in both modes — the blue a link reads as when no credit line has resolved, rather than the near-black/near-white it used to inherit from the text ramp.
    /// BRAND-DERIVED. This value is the neutral fallback — used before a credit line resolves, and by any brand-agnostic surface (marketing, a program-less login screen). Once a credit line is known, the runtime brand engine (tokens/brand-engine.md) overrides this same identifier with that credit line's accent tone; the swap is a cross-fade, not a reload.
    public static let textLink = Color.qf(0x0867B1, 0x87C2FE)
    /// The caret in a text field. Nothing else.
    /// BRAND-DERIVED, to the same value as border/focus — a caret and a focus ring are one signal on one control, both saying THIS is where typing goes. This value is the neutral fallback shown before a credit line resolves.
    /// Left unbound, Material resolves the caret to its primary slot, which in this system is action/filled/neutral charcoal — a credit line's field would blink in QuickFi's grey.
    /// Rated as a graphic (3:1), not as text: a caret is a thin mark, not something anyone reads. Measured against container/subsurface, container/surface and container/background.
    public static let textCursor = Color.qf(0x0B0A0F, 0xF3F3F6)
    /// The wash behind selected text INSIDE a field. Nothing else.
    /// BRAND-DERIVED, and deliberately NOT the same token as action/selected. A selected row sits on container/surface or surface-1; selected text sits in the container/subsurface well of an input. Different backdrop, different separation obligation, so they cannot share one value — the two only share a starting point, because the neutral is the neutral.
    /// text/primary must clear 4.5:1 on it. That is the pairing Material never audits, and the reason an unbound selection wash is a risk on a recessed field.
    public static let textSelectionBg = Color.qf(0xC9C9CE, 0x494844)

    // MARK: - Border
    /// Hairlines, dividers, input strokes, table rules — and the border of a DISABLED outline button.
    /// NOT a control boundary: at 1.48:1 it cannot carry one.
    public static let border = Color.qf(0xD4D4D4, 0x54545D)
    /// Focus ring.
    /// 2pt, never thinner.
    /// BRAND-DERIVED, same override relationship as textLink: this value is the neutral fallback pre-resolution; the runtime brand engine (tokens/brand-engine.md) supplies the credit line's tone once known.
    public static let borderFocus = Color.qf(0x0B0A0F, 0xF3F3F6)

    // MARK: - Action
    /// FILLED button, NEUTRAL intent — filled weight without a brand claim: Manage, View statement.
    /// Charcoal-anchored. Pair with textOnAction.
    public static let actionFilledNeutral = Color.qf(0x3A3A3C, 0xEDEDED)
    /// Hover state of a neutral filled button — web only.
    /// Pair with textOnAction.
    public static let actionFilledNeutralHover = Color.qf(0x313133, 0xF2F2F2)
    /// Pressed state of a neutral filled button.
    public static let actionFilledNeutralPressed = Color.qf(0x28282A, 0xF7F7F7)
    /// FILLED button, NOTIFY intent — notification and announcement actions.
    /// Same purple as feedback/notify at the base state. Pair with textOnAction.
    public static let actionFilledNotify = Color.qf(0x8B37C3, 0xA96CD3)
    /// Hover state of a notify filled button — web only.
    /// Pair with textOnAction.
    public static let actionFilledNotifyHover = Color.qf(0x7F31B4, 0xB27AD8)
    /// Pressed state of a notify filled button.
    public static let actionFilledNotifyPressed = Color.qf(0x7229A5, 0xBB88DE)
    /// FILLED button, DANGER intent — terminal and destructive actions: Delete, Cancel contract.
    /// Never the primary path; always behind a confirmation.
    /// Same red family as feedback/badge. Pair with textOnAction.
    public static let actionFilledDanger = Color.qf(0xC8102E, 0xFF8983)
    /// Hover state of a danger filled button — web only.
    /// Pair with textOnAction.
    public static let actionFilledDangerHover = Color.qf(0xB40E27, 0xFF938E)
    /// Pressed state of a danger filled button.
    public static let actionFilledDangerPressed = Color.qf(0xA00C22, 0xFF9E99)
    /// FILLED button, SUCCESS intent — a positive, affirming action the product itself calls out: Save, Approve, Complete.
    /// Aligned to feedback/success, NOT to brand/green — this is a status hue every credit line shares identically, not QuickFi's own per-credit-line seed. Pair with textOnActionSuccess, never textOnAction (white fails 4.5:1 against this fill in both modes).
    public static let actionFilledSuccess = Color.qf(0x2E9F3C, 0x56B25C)
    /// Hover state of a success filled button — web only.
    /// Pair with textOnActionSuccess.
    public static let actionFilledSuccessHover = Color.qf(0x2A9237, 0x64B869)
    /// Pressed state of a success filled button.
    public static let actionFilledSuccessPressed = Color.qf(0x288C35, 0x6ABB70)
    /// FILLED button, INFO intent — an advisory action the product surfaces alongside an informational message: View details, See schedule, Learn how this works.
    /// Aligned to feedback/info, the same way SUCCESS is aligned to feedback/success — a status hue every credit line shares identically, never a per-credit-line tone. Pair with textOnAction, which SUCCESS could not do: white clears 4.5:1 on this fill in light (4.60:1) where it fails on the success green.
    /// That 4.60:1 is the thinnest label margin of any filled intent. Both state layers move AWAY from it — darker in light, lighter in dark — so hover and pressed are safer than rest, not riskier; do not re-tune the base lighter without re-measuring.
    public static let actionFilledInfo = Color.qf(0x1778C9, 0x66A3E2)
    /// Hover state of an info filled button — web only.
    /// Pair with textOnAction.
    public static let actionFilledInfoHover = Color.qf(0x156EB9, 0x72AAE4)
    /// Pressed state of an info filled button.
    public static let actionFilledInfoPressed = Color.qf(0x146AB1, 0x78AEE5)
    /// The ONE disabled fill, shared by every intent — a dead button has no intent.
    /// Desaturated — reads inert, not brand.
    /// Pair with textOnActionDisabled.
    public static let actionFilledDisabled = Color.qf(0xDDDDE7, 0x494950)
    /// Border of an OUTLINE button. border/default cannot do this job — it is a hairline at 1.48:1, and a control boundary needs 3:1.
    /// Set equal to text/secondary's value, so the border and the label read as one weight instead of a faint hairline under a bold label. Kept as its own identifier rather than merged into text/secondary — a border is audited as a graphic pairing (3:1), a label as text (4.5:1), and the two are only coincidentally the same colour today.
    public static let actionOutline = Color.qf(0x3B3B3B, 0xE6E6E6)
    /// Border of a DISABLED OUTLINE button. Nothing else.
    /// Set equal to text/disabled's value, the same way action/outline is set equal to text/secondary's: a control's boundary and its label are one signal, so they move together. border/default was standing in for this and could not — its own doc says a 1.48:1 hairline is not a control boundary.
    /// Deliberately BELOW the 3:1 that WCAG 1.4.11 asks of a control boundary — 2.39:1 in light, 2.40:1 in dark. 1.4.11 exempts inactive components by name, and a disabled control that clears the active threshold is a disabled control that looks enabled. Audited as separation (1.10) against container/surface and container/background, because the real obligation is that the boundary be visible at all.
    public static let actionOutlineDisabled = Color.qf(0xA7A7AD, 0x68686F)
    /// The ONLY token in the system whose job is purely interaction state, not structure.
    /// Pressed fill for an OUTLINE or TEXT button; fill for a selected row, chip or tab.
    /// Audited against both container/surface and container/surface-1 — the two real layers it sits on top of — not just one.
    /// Takes textPrimary only — textLink is not rated on it, same as container/subsurface.
    /// BRAND-DERIVED. This value is the neutral fallback used before a credit line resolves; the runtime brand engine (tokens/brand-engine.md) then washes it with that credit line's hue, one chroma step stronger than the container wash, and keeps its own separation floors — including one against action/filled/disabled that no static audit ever measured.
    public static let actionSelected = Color.qf(0xC9C9CE, 0x494844)

    // MARK: - Brand accent
    /// Chip fills, an emphasis or progress bar. Never a button fill.
    /// BRAND-DERIVED. This value is the neutral fallback — identical to actionFilledNeutral — used before a credit line resolves. Once known, the runtime brand engine (tokens/brand-engine.md) overrides this identifier with that credit line's accent tone.
    public static let brandAccent = Color.qf(0x3A3A3C, 0xEDEDED)
    /// Hover state of a brand/accent fill — web only.
    /// BRAND-DERIVED, same override relationship as brand/accent. Fallback equals actionFilledNeutralHover.
    public static let brandAccentHover = Color.qf(0x313133, 0xF2F2F2)
    /// Pressed state of a brand/accent fill.
    /// BRAND-DERIVED, same override relationship as brand/accent. Fallback equals actionFilledNeutralPressed.
    public static let brandAccentPressed = Color.qf(0x28282A, 0xF7F7F7)
    /// Label on a brand/accent fill. Nothing else.
    /// BRAND-DERIVED. Fallback equals textOnAction — the same fallback Theme.kt's onTertiary slot already used before this token existed statically.
    public static let textOnBrand = Color.qf(0xFFFFFF, 0x090C08)
    /// One more tinted tonal surface than the ambient container wash: a credit-line hero card or program switcher. Nowhere else.
    /// BRAND-DERIVED. Fallback equals actionSelected's value — the same fallback Theme.kt's tertiaryContainer slot already used before this token existed statically.
    public static let brandBackground = Color.qf(0xC9C9CE, 0x494844)
    /// Label on brand/background. Nothing else.
    /// BRAND-DERIVED. Fallback equals textPrimary — the same fallback Theme.kt's onTertiaryContainer slot already used before this token existed statically.
    public static let textOnBrandBackground = Color.qf(0x0B0A0F, 0xF3F3F6)

    // MARK: - Feedback
    /// Error: icon glyphs, solid fills, 2px borders.
    public static let error = Color.qf(0xF55155, 0xF97774)
    /// Error: text sitting on the tint.
    public static let errorText = Color.qf(0xC1152B, 0xFFA19D)
    /// Error: the tint itself.
    public static let errorBg = Color.qf(0xFFE7E4, 0x562D2C)
    /// Warning: icon glyphs, solid fills, 2px borders.
    public static let warning = Color.qf(0xC77912, 0xD19251)
    /// Warning: text sitting on the tint.
    public static let warningText = Color.qf(0x9B5100, 0xEDB073)
    /// Warning: the tint itself.
    public static let warningBg = Color.qf(0xFFEEDD, 0x4A3623)
    /// Success: icon glyphs, solid fills, 2px borders.
    public static let success = Color.qf(0x2E9F3C, 0x56B25C)
    /// Success: text sitting on the tint.
    public static let successText = Color.qf(0x007700, 0x70CB74)
    /// Success: the tint itself.
    public static let successBg = Color.qf(0xE0FAE0, 0x243C25)
    /// Info: icon glyphs, solid fills, 2px borders.
    public static let info = Color.qf(0x1778C9, 0x66A3E2)
    /// Info: text sitting on the tint.
    public static let infoText = Color.qf(0x0867B1, 0x87C2FE)
    /// Info: the tint itself.
    public static let infoBg = Color.qf(0xE3F4FF, 0x293C50)
    /// Notify: icon glyphs, solid fills, 2px borders.
    /// Its solid also serves as an action fill — buttons bind to action/filled/notify, which carries the same base value.
    public static let notify = Color.qf(0x8B37C3, 0xA96CD3)
    /// Notify: text sitting on the tint.
    public static let notifyText = Color.qf(0x8548AC, 0xD9A7FE)
    /// Notify: the tint itself.
    public static let notifyBg = Color.qf(0xFBEAFF, 0x433250)
    /// The count badge: unread counts, cart totals, alert tallies.
    /// A solid fill whose numeral is textOnBadge. Not a status — no -text or -bg role.
    /// Never use feedback/error as a badge fill; it is a graphics red at 3.4:1.
    public static let badge = Color.qf(0xC8102E, 0xFF8983)

    // MARK: - Elevation
    /// The colour every shadow on every platform draws from. Never a fill, never a stroke, never text.
    /// Near-black in light and PURE black in dark. Dark needs the extra depth because a shadow there has to darken container/background #242424 rather than a near-white page — the same near-black used in light is barely distinguishable from the surface it falls on.
    /// Alphas belong to the elevation LEVEL, not to this token: lifted .08/.04, raised .10/.06, floating .12/.08 in light, and roughly four to five times those in dark. Two layers per level, a broad ambient pass and a tight contact pass.
    /// Exempt from the dark-ladder rule. Pure black sits below container/background by construction, which is the point of a shadow and not the hole that rule looks for.
    public static let shadowTint = Color.qf(0x0B0A0F, 0x000000)
}

/// The same tokens as `QuickFiColor`, typed `UIColor` for UIKit call sites.
/// One identifier per token, same name in both enums; the doc comments live
/// on `QuickFiColor` and are not repeated here.
public enum QuickFiUIColor {

    // MARK: - Brand
    public static let brandGreen = UIColor.qf(0x25AB3A, 0x25AB3A)
    public static let brandCharcoal = UIColor.qf(0x3A3A3C, 0x3A3A3C)

    // MARK: - Container
    public static let background = UIColor.qf(0xF1F1F4, 0x242424)
    public static let surface = UIColor.qf(0xFFFFFF, 0x2C3036)
    public static let surface1 = UIColor.qf(0xE3E3E8, 0x393834)
    public static let surface2 = UIColor.qf(0xD6D6DB, 0x41403C)
    public static let subsurface = UIColor.qf(0xD8D8DB, 0x3C3C44)
    public static let backgroundWash = UIColor.qf(0xF1F1F4, 0x242424)
    public static let backgroundWashHaze = UIColor.qf(0xF1F1F4, 0x242424)

    // MARK: - Text
    public static let textPrimary = UIColor.qf(0x0B0A0F, 0xF3F3F6)
    public static let textSecondary = UIColor.qf(0x3B3B3B, 0xE6E6E6)
    public static let textTertiary = UIColor.qf(0x6D6D72, 0x9999A0)
    public static let textDisabled = UIColor.qf(0xA7A7AD, 0x68686F)
    public static let textOnAction = UIColor.qf(0xFFFFFF, 0x090C08)
    public static let textOnActionDisabled = UIColor.qf(0x606067, 0xBABAC1)
    public static let textOnBadge = UIColor.qf(0xFFFFFF, 0x090C08)
    public static let textOnActionSuccess = UIColor.qf(0xFFFFFF, 0x0B0A0F)
    public static let textLink = UIColor.qf(0x0867B1, 0x87C2FE)
    public static let textCursor = UIColor.qf(0x0B0A0F, 0xF3F3F6)
    public static let textSelectionBg = UIColor.qf(0xC9C9CE, 0x494844)

    // MARK: - Border
    public static let border = UIColor.qf(0xD4D4D4, 0x54545D)
    public static let borderFocus = UIColor.qf(0x0B0A0F, 0xF3F3F6)

    // MARK: - Action
    public static let actionFilledNeutral = UIColor.qf(0x3A3A3C, 0xEDEDED)
    public static let actionFilledNeutralHover = UIColor.qf(0x313133, 0xF2F2F2)
    public static let actionFilledNeutralPressed = UIColor.qf(0x28282A, 0xF7F7F7)
    public static let actionFilledNotify = UIColor.qf(0x8B37C3, 0xA96CD3)
    public static let actionFilledNotifyHover = UIColor.qf(0x7F31B4, 0xB27AD8)
    public static let actionFilledNotifyPressed = UIColor.qf(0x7229A5, 0xBB88DE)
    public static let actionFilledDanger = UIColor.qf(0xC8102E, 0xFF8983)
    public static let actionFilledDangerHover = UIColor.qf(0xB40E27, 0xFF938E)
    public static let actionFilledDangerPressed = UIColor.qf(0xA00C22, 0xFF9E99)
    public static let actionFilledSuccess = UIColor.qf(0x2E9F3C, 0x56B25C)
    public static let actionFilledSuccessHover = UIColor.qf(0x2A9237, 0x64B869)
    public static let actionFilledSuccessPressed = UIColor.qf(0x288C35, 0x6ABB70)
    public static let actionFilledInfo = UIColor.qf(0x1778C9, 0x66A3E2)
    public static let actionFilledInfoHover = UIColor.qf(0x156EB9, 0x72AAE4)
    public static let actionFilledInfoPressed = UIColor.qf(0x146AB1, 0x78AEE5)
    public static let actionFilledDisabled = UIColor.qf(0xDDDDE7, 0x494950)
    public static let actionOutline = UIColor.qf(0x3B3B3B, 0xE6E6E6)
    public static let actionOutlineDisabled = UIColor.qf(0xA7A7AD, 0x68686F)
    public static let actionSelected = UIColor.qf(0xC9C9CE, 0x494844)

    // MARK: - Brand accent
    public static let brandAccent = UIColor.qf(0x3A3A3C, 0xEDEDED)
    public static let brandAccentHover = UIColor.qf(0x313133, 0xF2F2F2)
    public static let brandAccentPressed = UIColor.qf(0x28282A, 0xF7F7F7)
    public static let textOnBrand = UIColor.qf(0xFFFFFF, 0x090C08)
    public static let brandBackground = UIColor.qf(0xC9C9CE, 0x494844)
    public static let textOnBrandBackground = UIColor.qf(0x0B0A0F, 0xF3F3F6)

    // MARK: - Feedback
    public static let error = UIColor.qf(0xF55155, 0xF97774)
    public static let errorText = UIColor.qf(0xC1152B, 0xFFA19D)
    public static let errorBg = UIColor.qf(0xFFE7E4, 0x562D2C)
    public static let warning = UIColor.qf(0xC77912, 0xD19251)
    public static let warningText = UIColor.qf(0x9B5100, 0xEDB073)
    public static let warningBg = UIColor.qf(0xFFEEDD, 0x4A3623)
    public static let success = UIColor.qf(0x2E9F3C, 0x56B25C)
    public static let successText = UIColor.qf(0x007700, 0x70CB74)
    public static let successBg = UIColor.qf(0xE0FAE0, 0x243C25)
    public static let info = UIColor.qf(0x1778C9, 0x66A3E2)
    public static let infoText = UIColor.qf(0x0867B1, 0x87C2FE)
    public static let infoBg = UIColor.qf(0xE3F4FF, 0x293C50)
    public static let notify = UIColor.qf(0x8B37C3, 0xA96CD3)
    public static let notifyText = UIColor.qf(0x8548AC, 0xD9A7FE)
    public static let notifyBg = UIColor.qf(0xFBEAFF, 0x433250)
    public static let badge = UIColor.qf(0xC8102E, 0xFF8983)

    // MARK: - Elevation
    public static let shadowTint = UIColor.qf(0x0B0A0F, 0x000000)
}
